name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PUBLISH_REGISTRY_PASSWORD }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
